**Download the SraRunTable.txt file from NCBI:**

This file contains the list of accessions (sequencing runs)

In [8]:
%%bash

time {

OUTDIR="/var/www/html/usb/jupyter/my_projects/data/SRP093363"
mkdir -p "$OUTDIR"

rm -f "$OUTDIR/SraRunTable.txt"

curl --http1.1 -L --retry 5 --retry-delay 10 \
  "https://trace.ncbi.nlm.nih.gov/Traces/sra-db-be/runinfo?acc=SRP093363" \
  -o "$OUTDIR/SraRunTable.txt"

ls -lh "$OUTDIR/SraRunTable.txt"
head -5 "$OUTDIR/SraRunTable.txt"

}

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6335    0  6335    0     0  15956      0 --:--:-- --:--:-- --:--:-- 15997

-rw-r--r-- 1 pi pi 6.2K May 17 07:05 /var/www/html/usb/jupyter/my_projects/data/SRP093363/SraRunTable.txt
Run,ReleaseDate,LoadDate,spots,bases,spots_with_mates,avgLength,size_MB,AssemblyName,download_path,Experiment,LibraryName,LibraryStrategy,LibrarySelection,LibrarySource,LibraryLayout,InsertSize,InsertDev,Platform,Model,SRAStudy,BioProject,Study_Pubmed_id,ProjectID,Sample,BioSample,SampleType,TaxID,ScientificName,SampleName,g1k_pop_code,source,g1k_analysis_group,Subject_ID,Sex,Disease,Tumor,Affection_Status,Analyte_Type,Histological_Type,Body_Site,CenterName,Submission,dbgap_study_accession,Consent,RunHash,ReadHash
SRR5017135,2017-01-01 00:00:00,2016-11-15 12:43:46,38618203,3900438503,0,101,2707,,https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos5/sra-pub-zq-11/SRR005/017/SRR5017135/SRR5017135.sralite.1,SRX2345618,HFD Con 1,RNA-Seq,other,TRANSCRIPTOMIC,SINGLE,0,0,ILLUMINA,Illumina HiSeq 2500,SRP093363,PRJNA353374,,353374,SRS1794108,SAMN06006082,simple,10090,Mus musculus,High-Fat Diet Control 1,,,,,male,,no,,,,,TULANE,SRA492971,,public,5C568A5D9E68D9FA1492A70AFDDF92BF,FA3737C86852C0FA29BF4F9F05041446
SRR5017137,2017-01-01 00:00:00,2016-11-14 12:50:27,52427951,5295223051,0,101,3661,,https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos5/sra-pub-zq-11/SRR005/017/SRR5017137/SRR5017137.sralite.1,SRX2345620,HFD Con 2,RNA-Seq,other,TRANSCRIPTOMIC,SINGLE,0,0,ILLUMINA,Illumina HiSeq 2500,SRP093363,PRJNA353374,,353374,SRS1794110,SAMN06006101,simple,10090,Mus musculus,High-Fat Diet Control 2,,,,,male,,no,,,,,TULANE,SRA492971,,public,DF818333743963FA14DC176FD7DAA19D,B6F7CF72ABFE90557EF8CB008E84D422
SRR5017133,2017-01-01 00:00:00,2016-11-14 12:47:45,55837914,5639629314,0,101,3901,,https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos5/sra-pub-zq-14/SRR005/017/SRR5017133.sralite.1,SRX2345616,HFD Con 3,RNA-Seq,other,TRANSCRIPTOMIC,SINGLE,0,0,ILLUMINA,Illumina HiSeq 2500,SRP093363,PRJNA353374,,353374,SRS1794106,SAMN06006102,simple,10090,Mus musculus,High-Fat Diet Control 3,,,,,male,,no,,,,,TULANE,SRA492971,,public,180482F5E8E3B66C77FDAA7477E958E5,A866F7556188514C0EBA1394E2AFE353
SRR5017132,2017-01-01 00:00:00,2016-11-14 12:45:24,41792519,4221044419,0,101,2933,,https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos5/sra-pub-zq-14/SRR005/017/SRR5017132.sralite.1,SRX2345615,HFD Tumor 1,RNA-Seq,other,TRANSCRIPTOMIC,SINGLE,0,0,ILLUMINA,Illumina HiSeq 2500,SRP093363,PRJNA353374,,353374,SRS1794105,SAMN06006145,simple,10090,Mus musculus,High-Fat Diet Tumor 1,,,,,male,,no,,,,,TULANE,SRA492971,,public,D773285A9C56F5F59D7F9DFF44B59EB5,B49661739E7767B608FB8F2DCCEE3FA1

real	0m0.414s
user	0m0.031s
sys	0m0.009s

**Display in a Table, the headings row and first two rows of data:**

Count across to the 'Samples' column starting at column zero first. In this case the 'Samples' column is column 24.

In [5]:
%%time 

import pandas as pd

OUTDIR="/var/www/html/usb/jupyter/my_projects/data/SRP093363"

# Show ALL columns
pd.set_option('display.max_columns', None)

# Optional: widen display
pd.set_option('display.width', None)

# Load file
df = pd.read_csv(f"{OUTDIR}/SraRunTable.txt")

# Display first 2 rows
df.head(2)

CPU times: user 519 ms, sys: 36.9 ms, total: 555 ms
Wall time: 1.02 s

,Run,ReleaseDate,LoadDate,spots,bases,spots_with_mates,avgLength,size_MB,AssemblyName,download_path,Experiment,LibraryName,LibraryStrategy,LibrarySelection,LibrarySource,LibraryLayout,InsertSize,InsertDev,Platform,Model,SRAStudy,BioProject,Study_Pubmed_id,ProjectID,Sample,BioSample,SampleType,TaxID,ScientificName,SampleName,g1k_pop_code,source,g1k_analysis_group,Subject_ID,Sex,Disease,Tumor,Affection_Status,Analyte_Type,Histological_Type,Body_Site,CenterName,Submission,dbgap_study_accession,Consent,RunHash,ReadHash
0,SRR5017135,2017-01-01 00:00:00,2016-11-15 12:43:46,38618203,3900438503,0,101,2707,NaN,https://sra-downloadb.be-md.ncbi.nlm.nih.gov/s...,SRX2345618,HFD Con 1,RNA-Seq,other,TRANSCRIPTOMIC,SINGLE,0,0,ILLUMINA,Illumina HiSeq 2500,SRP093363,PRJNA353374,NaN,353374,SRS1794108,SAMN06006082,simple,10090,Mus musculus,High-Fat Diet Control 1,NaN,NaN,NaN,NaN,male,NaN,no,NaN,NaN,NaN,NaN,TULANE,SRA492971,NaN,public,5C568A5D9E68D9FA1492A70AFDDF92BF,FA3737C86852C0FA29BF4F9F05041446
1,SRR5017137,2017-01-01 00:00:00,2016-11-14 12:50:27,52427951,5295223051,0,101,3661,NaN,https://sra-downloadb.be-md.ncbi.nlm.nih.gov/s...,SRX2345620,HFD Con 2,RNA-Seq,other,TRANSCRIPTOMIC,SINGLE,0,0,ILLUMINA,Illumina HiSeq 2500,SRP093363,PRJNA353374,NaN,353374,SRS1794110,SAMN06006101,simple,10090,Mus musculus,High-Fat Diet Control 2,NaN,NaN,NaN,NaN,male,NaN,no,NaN,NaN,NaN,NaN,TULANE,SRA492971,NaN,public,DF818333743963FA14DC176FD7DAA19D,B6F7CF72ABFE90557EF8CB008E84D422

**Display the contents of column 0, column 24 and column 29 only:**

There are 12 SRS sample files in this project, however we are only interested in the samples

In [9]:
%%time 

import pandas as pd

OUTDIR="/var/www/html/usb/jupyter/my_projects/data/SRP093363"

# Load the file
df = pd.read_csv(f"{OUTDIR}/SraRunTable.txt")

# Display column 0 (Run), column 24 (Sample) and 29 (SampleName) only
df.iloc[:, [0,24,29]]

CPU times: user 6.32 ms, sys: 255 μs, total: 6.57 ms
Wall time: 10.3 ms

           Run      Sample               SampleName
0   SRR5017135  SRS1794108  High-Fat Diet Control 1
1   SRR5017137  SRS1794110  High-Fat Diet Control 2
2   SRR5017133  SRS1794106  High-Fat Diet Control 3
3   SRR5017132  SRS1794105    High-Fat Diet Tumor 1
4   SRR5017128  SRS1794101    High-Fat Diet Tumor 2
5   SRR5017138  SRS1794111    High-Fat Diet Tumor 3
6   SRR5017139  SRS1794112   Regular Diet Control 1
7   SRR5017129  SRS1794102   Regular Diet Control 2
8   SRR5017136  SRS1794109   Regular Diet Control 3
9   SRR5017134  SRS1794107     Regular Diet Tumor 1
10  SRR5017131  SRS1794104     Regular Diet Tumor 2
11  SRR5017130  SRS1794103     Regular Diet Tumor 3

**Get accession RUN numbers of interest:**

As can be seen above, there are 12 sample files in this project. Each of these files is between 3 and 4 GB in size. It can take from minutes to hours to download files of this size, depending on your interent speed. Therefore, we only download files which we are interested in. In this case we are interested in samples related to "High-Fat Diet Control" and "High-Fat Diet Tumor". Here we extract those accession RUN numbers and put them into a new file named finalsamples.txt.

In [10]:
%%time 

import pandas as pd

OUTDIR="/var/www/html/usb/jupyter/my_projects/data/SRP093363"

# Load the file
df = pd.read_csv(f"{OUTDIR}/SraRunTable.txt")

# -----------------------------
# High-Fat Diet Control
# -----------------------------
control = df[
    df.iloc[:, 29].astype(str).str.contains(
        "High-Fat Diet Control",
        case=False,
        na=False
    )
# ].iloc[:, [0, 24, 29]]
].iloc[:, [0]] # Only keep Run data

# Save first dataset
control.to_csv(
    f"{OUTDIR}/finalsamples.txt",
    index=False,
    header=False
)

# -----------------------------
# High-Fat Diet Tumor
# -----------------------------
tumor = df[
    df.iloc[:, 29].astype(str).str.contains(
        "High-Fat Diet Tumor",
        case=False,
        na=False
    )
# ].iloc[:, [0, 24, 29]]
].iloc[:, [0]] # Only keep Run data

# Append to same file
tumor.to_csv(
    f"{OUTDIR}/finalsamples.txt",
    mode='a',
    index=False,
    header=False
)

# Display both
display(control)
display(tumor)

          Run
0  SRR5017135
1  SRR5017137
2  SRR5017133

          Run
3  SRR5017132
4  SRR5017128
5  SRR5017138

CPU times: user 17 ms, sys: 4.11 ms, total: 21.1 ms
Wall time: 30.6 ms

**Download the SRA RUN files of interest based on the 'finalsamples.txt' file contents:**

In [ ]:
%%bash

time {

OUTDIR="/var/www/html/usb/jupyter/my_projects/data/SRP093363"

cut -d',' -f1 "$OUTDIR/finalsamples.txt" | while read SRR; do

    # Clean hidden characters/spaces
    SRR=$(echo "$SRR" | tr -d '\r' | xargs)

    # Skip empty lines
    [ -z "$SRR" ] && continue

    # Expected SRA file path
    SRA_FILE="$OUTDIR/$SRR/$SRR.sra"

    # Skip if already downloaded
    if [ -f "$SRA_FILE" ]; then
        echo "Skipping $SRR (already exists)"
        continue
    fi

    echo "Downloading $SRR ..."

    prefetch "$SRR" --output-directory "$OUTDIR/sra"

done
}

**Convert SRA files to FASTQ files:**

Note: An SRA file of ~4GB will convert to fastq file ~13GB

In [ ]:
%%bash

time {

SRA_DIR="/var/www/html/usb/jupyter/my_projects/data/SRP093363/sra"
FASTQ_DIR="/var/www/html/usb/jupyter/my_projects/data/SRP093363/fastq"

mkdir -p "$FASTQ_DIR"

find "$SRA_DIR" -name "*.sra" | while read FILE; do

    BASENAME=$(basename "$FILE" .sra)

    FASTQ1="$FASTQ_DIR/${BASENAME}_1.fastq"
    FASTQ2="$FASTQ_DIR/${BASENAME}_2.fastq"
    FASTQ_SINGLE="$FASTQ_DIR/${BASENAME}.fastq"

    # Skip if FASTQ already exists
    if [ -f "$FASTQ1" ] || [ -f "$FASTQ_SINGLE" ]; then
        echo "Skipping $BASENAME (FASTQ already exists)"
        continue
    fi

    echo "Converting $BASENAME ..."

    fasterq-dump "$FILE" \
        --split-files \
        --threads 4 \
        --outdir "$FASTQ_DIR"
}
done

Converting SRR5017132 ...

**Delete all of the sra files and folders located inside the sra folder:**

This will free up about 3 to 4 GB per SRA file.

In [2]:
%%bash

time {
    
rm -rf "/var/www/html/usb/jupyter/my_projects/data/SRP093363/sra"/SRR*
    
}

real	0m0.072s
user	0m0.000s
sys	0m0.066s

**gzip the output FASTQ files:**

Note: A fastq file of ~13GB will be compressed to a fastq.gz file of ~4GB

In [1]:
%%bash

FASTQ_DIR="/var/www/html/usb/jupyter/my_projects/data/SRP093363/fastq"

# Change the dir name to:
# FASTQ_DIR="/var/www/html/usb/jupyter/my_projects/data/SRP093363/fastq_gz"

for file in "$FASTQ_DIR"/*.fastq; do

    # Skip if no .fastq files exist
    [ -e "$file" ] || continue

    gz_file="${file}.gz"

    if [ -f "$gz_file" ]; then
        echo "Skipping: $(basename "$file") -> .gz already exists"
    else
        echo "Compressing: $(basename "$file")"
        gzip "$file"
    fi

done

echo "Finished."

Skipping: SRR5017135.fastq -> .gz already exists
Skipping: SRR5017138.fastq -> .gz already exists
Finished.

**Delete the original .fastq files that have matching .fastq.gz files:**

In [3]:
%%bash

FASTQ_DIR="/var/www/html/usb/jupyter/my_projects/data/SRP093363/fastq"

for file in "$FASTQ_DIR"/*.fastq; do
    [ -e "$file" ] || continue

    if [ -f "${file}.gz" ]; then
        echo "Deleting: $(basename "$file")"
        rm "$file"
    fi
done

echo "Finished."

Deleting: SRR5017135.fastq
Deleting: SRR5017138.fastq
Finished.